### ISSUE TITLE
装机小记

### ISSUE THREAD

**Issue by Chever-John** [AlynxZhou/stackharbor#43]
你食言了哦，没有直播哦今天

**Comment by AlynxZhou** [comment]
> 你食言了哦，没有直播哦今天

在家，只有笔记本，我自己打点游戏都费劲

**Comment by Mr8god** [comment]
哈哈哈

**Comment by AlynxZhou** [comment]
你既然开了评论就别关了，关了就不显示了

**Comment by Chever-John** [comment]
好家伙，我看着这也没啥一直开着的必要性呀emmmm

**Comment by AlynxZhou** [comment]
> 好家伙，我看着这也没啥一直开着的必要性呀emmmm

我不知道关了以后再评论的话能不能创建同名的 issue，处理起来很麻烦
