### ISSUE TITLE
吐槽频道

### ISSUE THREAD

**Issue by hibobmaster** [AlynxZhou/stackharbor#48]
發現大佬提交的包
https://aur.archlinux.org/packages/gnome-shell-extension-simple-net-speed/

**Comment by AlynxZhou** [comment]
@hibobmaster 你提醒我了，作者发了新 Release 了，我要去更新……

**Comment by 1169927533** [comment]
FlipClock那个项目打不开，报：could not find libmain.so

**Comment by AlynxZhou** [comment]
> FlipClock那个项目打不开，报：could not find libmain.so

Linux下面需要装SDL的，然后你这信息太少了，猜不出来怎么回事。最后FlipClock有自己的issue页面，比这里更适合报bug。
