### ISSUE TITLE
奇怪的书名和我和吐槽

### ISSUE THREAD

**Issue by dongshunyao** [AlynxZhou/stackharbor#49]
《如何阅读一本书》这书还是挺有名的，虽然比较标题党，但还是值得一读XD

**Comment by jingyig01** [comment]
《如何阅读一本书》：虽然名字很奇怪，内容还是很有价值的。我读过几遍，感觉颇有收获。
木心：我读过他的诗集，感觉一般。好像是因为《从前慢》火起来的。相比之下，我更喜欢海子的诗歌。
蒋勋和张小娴差不多是网红作家啦。前者致力于“向大众推广古典艺术”，写了一堆关于唐诗宋词艺术史的书。说实在话，我不太相信一个人能同时精通那么多学科...所以我基本不读他的书。后者是零几年时特别火的流行作家，出了不少“爱情疗愈系”的书。不读也罢。
书名嘛，就不要过分纠结了。杨绛那本书让我想起我高中做阅读理解时，读的王安忆的《洗澡》。话说回来，有段时间我总是分不清钱钟书的《围城》和沈从文的《边城》 233

**Comment by hamkido** [comment]
《如何阅读一本书》很值得一读,强烈推荐.

**Comment by Radcliffe-Bai** [comment]
《如何阅读一本书》是我小学就已经买了看的书（虽然被同学看到后也吐槽过这个书名）😆
