### ISSUE TITLE
X 和 Wayland 的主要区别

### ISSUE THREAD

**Issue by shenlebantongying** [AlynxZhou/stackharbor#52]
Hao wen.

**Comment by AlynxZhou** [comment]
你在干嘛？再不停开关 issue 的话我就把你当成 spam 邮件屏蔽了

**Comment by shenlebantongying** [comment]
我发现关 issuse 以后就不会在博客里面显示了，于是多点了一轮试验一下 `:)`

**Comment by yuhangch** [comment]
很有趣，比看百科了解的快多了

**Comment by ACupofAir** [comment]
大佬牛皮，通俗易懂

**Comment by shenlebantongying** [comment]
我觉得除了技术细节，Wayland 还更符合开源社区的开发模式。相比起只有一个桌面环境的 win/mac，Linux 桌面必然是分裂的。X 定义了很多东西，导致各个桌面环境依赖 X 的一些行为才能正常工作。比如说很久以前同时装 GNOME 和 KDE 就会因为它们对一些 X 的相关配置理解不一样有各种各样的问题。去动 X 就很容易导致下游的软件出问题，现在那些不必要的东西下放到各个桌面环境里去实现，直接解放了桌面环境和 Wayland/X 两边的开发者, 也让软件更加可靠。
