### ISSUE TITLE
不应该做 EVA，而应该做环太平洋

### ISSUE THREAD

**Issue by dongshunyao** [AlynxZhou/stackharbor#66]
沙发！
我不管，扳机社YYDS！

**Comment by AlynxZhou** [comment]
> 沙发！ 我不管，扳机社YYDS！

从美术角度来说，确实了不起。

**Comment by dongshunyao** [comment]
> > 沙发！ 我不管，扳机社YYDS！
> 
> 从美术角度来说，确实了不起。

信じる心があなたの魔法〜

**Comment by catscarlet** [comment]
EVA如果算作标杆的话那大概没什么作品能爬到杆子一半的高度，这杆子实在太高了。
